# Generated by Django 3.1 on 2020-08-27 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(verbose_name='текущий баланс на счете'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='ФИО абонента'),
        ),
        migrations.AlterField(
            model_name='account',
            name='hold',
            field=models.IntegerField(verbose_name='холды на счете'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=True, verbose_name='статус счета'),
        ),
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный номер абонента'),
        ),
    ]
