# Generated by Django 3.1 on 2020-08-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200827_1540'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
    ]
