# Generated by Django 3.1 on 2020-08-28 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200827_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='текущий баланс на счете'),
        ),
        migrations.AlterField(
            model_name='account',
            name='hold',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='холды на счете'),
        ),
    ]
